class_name ItemPipeline
extends RefCounted
## Items data pipeline: data/items/items.csv (one row per item) -> one generated EquipmentData .tres per row in
## resources/items/. The table is the only place items are edited; the generated files carry a header that says
## so, and check() reports any that differ from what the table makes (edited by hand, stale or missing).
## Used by tools/items/item_generator.gd (writes) and the items test (checks).

const ITEMS_TABLE: String = "res://data/items/items.csv"
const OUTPUT_DIR: String = "res://resources/items/"
const EQUIPMENT_SCRIPT: String = "res://scripts/resources/equipment_data.gd"
## Columns of items.csv, in order. "overrides" = per-item stat overrides for special items (stage 2).
const COLUMNS: Array[String] = ["id", "name", "slot", "tier", "role", "set_id", "sprite", "source", "overrides"]
## Every generated file starts with these lines (";" lines are comments in a .tres).
const HEADER: String = "; GENERATED by tools/items/item_generator.gd from data/items/items.csv - DO NOT EDIT.\n" \
	+ "; Change the table, then run:  <godot.exe> --headless --path . -- --generate-items\n"


## One table row (column name -> text), plus where it came from for error messages.
class Row:
	var line: int
	var values: Dictionary = {}

	func get_value(column: String) -> String:
		return values.get(column, "")


## The table's rows, or an empty list with `errors` filled when the table can't be read.
static func read_table(errors: Array[String], path: String = ITEMS_TABLE) -> Array[Row]:
	var rows: Array[Row] = []
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		errors.append("%s: can't open it" % path)
		return rows
	var header: PackedStringArray = file.get_csv_line()
	if Array(header) != COLUMNS:
		errors.append("%s: the columns must be exactly %s (found %s)" % [path, ",".join(COLUMNS), ",".join(header)])
		return rows
	var line: int = 1
	while not file.eof_reached():
		var fields: PackedStringArray = file.get_csv_line()
		line += 1
		if fields.size() == 1 and fields[0].strip_edges().is_empty():
			continue
		if fields.size() != COLUMNS.size():
			errors.append("%s line %d: %d columns, expected %d" % [path, line, fields.size(), COLUMNS.size()])
			continue
		var row := Row.new()
		row.line = line
		for i in COLUMNS.size():
			row.values[COLUMNS[i]] = fields[i].strip_edges()
		rows.append(row)
	return rows


## Basic shape of a row (enough to generate it). The full checks are the validator's job (stage 5).
static func row_errors(row: Row) -> Array[String]:
	var errors: Array[String] = []
	var where: String = "items.csv line %d" % row.line
	if not row.get_value("id").is_valid_identifier():
		errors.append("%s: id \"%s\" must be letters, digits and _" % [where, row.get_value("id")])
	var slot: int = EquipmentData.slot_from_name(row.get_value("slot"))
	if slot < 0 or slot in EquipmentData.LOOK_SLOTS:
		errors.append("%s: unknown item slot \"%s\"" % [where, row.get_value("slot")])
	if not row.get_value("tier").is_valid_int() or row.get_value("tier").to_int() < 1:
		errors.append("%s: tier \"%s\" must be a whole number from 1" % [where, row.get_value("tier")])
	for column in ["name", "role", "sprite", "source"]:
		if row.get_value(column).is_empty():
			errors.append("%s: %s is empty" % [where, column])
	return errors


static func output_path(id: String) -> String:
	return OUTPUT_DIR + id + ".tres"


## The exact text of the generated .tres for a row.
static func item_text(row: Row) -> String:
	var lines: PackedStringArray = [
		"[gd_resource type=\"Resource\" script_class=\"EquipmentData\" format=3]",
		"",
		"[ext_resource type=\"Script\" path=\"%s\" id=\"1_item\"]" % EQUIPMENT_SCRIPT,
		"",
		"[resource]",
		"script = ExtResource(\"1_item\")",
		"id = &%s" % _quote(row.get_value("id")),
		"display_name = %s" % _quote(row.get_value("name")),
		"slot = %d" % EquipmentData.slot_from_name(row.get_value("slot")),
		"lpc_item = %s" % _quote(row.get_value("sprite")),
		"tier = %d" % row.get_value("tier").to_int(),
		"role = &%s" % _quote(row.get_value("role")),
		"set_id = &%s" % _quote(row.get_value("set_id")),
		"source = &%s" % _quote(row.get_value("source")),
	]
	return HEADER + "\n".join(lines) + "\n"


## Path -> text of every file the table makes. Errors (bad rows, duplicate ids) go to `errors`.
static func expected_files(errors: Array[String]) -> Dictionary:
	var files: Dictionary = {}
	for row in read_table(errors):
		var row_problems: Array[String] = row_errors(row)
		if not row_problems.is_empty():
			errors.append_array(row_problems)
			continue
		var path: String = output_path(row.get_value("id"))
		if files.has(path):
			errors.append("items.csv line %d: id \"%s\" is used twice" % [row.line, row.get_value("id")])
			continue
		files[path] = item_text(row)
	return files


## Generated files that don't match the table: edited by hand, missing, or left over from a removed row.
static func check() -> Array[String]:
	var problems: Array[String] = []
	var files: Dictionary = expected_files(problems)
	for path: String in files:
		if not FileAccess.file_exists(path):
			problems.append("%s is missing: run --generate-items" % path)
		elif FileAccess.get_file_as_string(path) != files[path]:
			problems.append("%s differs from the table (edited by hand?): run --generate-items" % path)
	for file in _generated_on_disk():
		if not files.has(OUTPUT_DIR + file):
			problems.append("%s%s has no row in the table: run --generate-items" % [OUTPUT_DIR, file])
	return problems


## Writes every file from the table and deletes generated files whose row is gone. Nothing is written when the
## table has errors. Returns the errors (empty = done); `report` gets what was written / removed.
static func generate(report: Array[String]) -> Array[String]:
	var errors: Array[String] = []
	var files: Dictionary = expected_files(errors)
	if not errors.is_empty():
		return errors
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUTPUT_DIR))
	for path: String in files:
		if FileAccess.file_exists(path) and FileAccess.get_file_as_string(path) == files[path]:
			continue
		var file := FileAccess.open(path, FileAccess.WRITE)
		if file == null:
			errors.append("%s: can't write it" % path)
			continue
		file.store_string(files[path])
		report.append("written " + path)
	for file in _generated_on_disk():
		if not files.has(OUTPUT_DIR + file):
			DirAccess.remove_absolute(ProjectSettings.globalize_path(OUTPUT_DIR + file))
			report.append("removed " + OUTPUT_DIR + file)
	return errors


## .tres files in the output folder (all of them are generated).
static func _generated_on_disk() -> Array[String]:
	var found: Array[String] = []
	for file in DirAccess.get_files_at(OUTPUT_DIR):
		if file.ends_with(".tres"):
			found.append(file)
	return found


static func _quote(text: String) -> String:
	return "\"%s\"" % text.replace("\\", "\\\\").replace("\"", "\\\"")
