class_name ItemPipeline
extends RefCounted
## Items data pipeline. The tables in data/items/ (explained in data/items/README.md):
##   stats.csv         every stat an item can have, and its kind (bonus / item / weapon)
##   roles.csv         every role (cloth, plate, dagger, bow, might...), its group, weapon properties
##   slot_rules.csv    every slot: its group, its share of the role values (scale), drawn on the character or not
##   tier_rules.csv    the stats of every role at every tier (F, D, C, B, A, S), one column per stat
##   slot_bonuses.csv  what every slot adds by itself at every tier (boots: speed, helmet: sight...)
##   items.csv         one row per item
## -> one generated EquipmentData .tres per item in resources/items/. The tables are the only place items are
## edited; the generated files carry a header that says so, and check() reports any that differ from what the
## tables make (edited by hand, stale or missing).
## An item's stats = tier rule of its role x its slot's scale + its slot's own bonus at that tier; the "special"
## column (special items only) sets exact values on top. Zeros are left out.
## Used by tools/items/item_generator.gd (writes) and the items test (checks).

const DATA_DIR: String = "res://data/items/"
const ITEMS_TABLE: String = DATA_DIR + "items.csv"
const STATS_TABLE: String = DATA_DIR + "stats.csv"
const ROLES_TABLE: String = DATA_DIR + "roles.csv"
const SLOT_RULES_TABLE: String = DATA_DIR + "slot_rules.csv"
const TIER_RULES_TABLE: String = DATA_DIR + "tier_rules.csv"
const SLOT_BONUSES_TABLE: String = DATA_DIR + "slot_bonuses.csv"
const OUTPUT_DIR: String = "res://resources/items/"
const EQUIPMENT_SCRIPT: String = "res://scripts/resources/equipment_data.gd"
## Columns of each table, in order. The two rule tables start with these and then have one column per stat
## (any stats of kind bonus or item from stats.csv; a missing column = 0 everywhere).
const COLUMNS: Array[String] = ["id", "name", "slot", "tier", "role", "set_id", "sprite", "source", "special"]
const STATS_COLUMNS: Array[String] = ["stat", "kind", "description"]
const ROLES_COLUMNS: Array[String] = ["role", "group", "melee", "splash", "attack_range"]
const SLOT_RULES_COLUMNS: Array[String] = ["slot", "group", "scale", "drawn"]
const TIER_RULES_FIRST: Array[String] = ["role", "tier"]
const SLOT_BONUSES_FIRST: Array[String] = ["slot", "tier"]
## Stat kinds: added to the wearer / a property of the item / a property of a weapon (from its role).
const KINDS: Array[String] = ["bonus", "item", "weapon"]
const WEAPON_GROUP: String = "weapon"
## Values are rounded to this step (0.001 = 0.1%).
const VALUE_STEP: float = 0.001
## Every generated file starts with these lines (";" lines are comments in a .tres).
const HEADER: String = "; GENERATED by tools/items/item_generator.gd from data/items/ - DO NOT EDIT.\n" \
	+ "; Change the tables, then run tools/generate_items.bat (or -- --generate-items).\n"


## One table row (column name -> text), plus where it came from for error messages.
class Row:
	var line: int
	var values: Dictionary = {}

	func get_value(column: String) -> String:
		return values.get(column, "")


## Everything the rule tables say, read once per generation.
class Rules:
	## stat -> kind
	var stat_kinds: Dictionary = {}
	## role -> Row of roles.csv
	var roles: Dictionary = {}
	## slot -> Row of slot_rules.csv
	var slots: Dictionary = {}
	## "role:tier" -> {stat: value}
	var tiers: Dictionary = {}
	## "slot:tier" -> {stat: value}
	var slot_bonuses: Dictionary = {}


## A table's rows, or an empty list with `errors` filled when the table can't be read.
## `columns` must match the header exactly; with `open_end`, they are only the first columns and the rest are
## returned in `extra_columns`.
static func read_table(errors: Array[String], path: String = ITEMS_TABLE, columns: Array[String] = COLUMNS,
		open_end: bool = false, extra_columns: Array[String] = []) -> Array[Row]:
	var rows: Array[Row] = []
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		errors.append("%s: can't open it" % path.get_file())
		return rows
	var header: Array[String] = []
	for column in file.get_csv_line():
		header.append(column.strip_edges())
	var fits: bool = header.slice(0, columns.size()) == columns if open_end else header == columns
	if not fits:
		errors.append("%s: the columns must %s %s (found %s)" % [path.get_file(), "start with" if open_end else "be exactly",
			",".join(columns), ",".join(header)])
		return rows
	extra_columns.assign(header.slice(columns.size()))
	var line: int = 1
	while not file.eof_reached():
		var fields: PackedStringArray = file.get_csv_line()
		line += 1
		if fields.size() == 1 and fields[0].strip_edges().is_empty():
			continue
		# Stat tables: a row may stop before the last columns (a stat column added at the end counts as empty there).
		if open_end and fields.size() >= columns.size() and fields.size() < header.size():
			fields.resize(header.size())
		if fields.size() != header.size():
			errors.append("%s line %d: %d columns, expected %d" % [path.get_file(), line, fields.size(), header.size()])
			continue
		var row := Row.new()
		row.line = line
		for i in header.size():
			row.values[header[i]] = fields[i].strip_edges()
		rows.append(row)
	return rows


## Tier letter (F, D, C, B, A, S) -> index, -1 if unknown.
static func tier_index(letter: String) -> int:
	return EquipmentData.TIER_NAMES.find(letter.to_upper())


## "crit_chance=0.05;knockback=0.3" -> {&"crit_chance": 0.05, &"knockback": 0.3}. Empty text = nothing.
static func parse_special(text: String, where: String, errors: Array[String]) -> Dictionary:
	var values: Dictionary = {}
	if text.is_empty():
		return values
	for pair in text.split(";", false):
		var parts: PackedStringArray = pair.split("=")
		var stat: String = parts[0].strip_edges() if parts.size() == 2 else ""
		var value: String = parts[1].strip_edges() if parts.size() == 2 else ""
		if not stat.is_valid_identifier() or not value.is_valid_float():
			errors.append("%s: \"%s\" must be stat=number (several separated by ;)" % [where, pair])
			continue
		if values.has(StringName(stat)):
			errors.append("%s: %s is given twice" % [where, stat])
		values[StringName(stat)] = value.to_float()
	return values


static func read_rules(errors: Array[String]) -> Rules:
	var rules := Rules.new()
	for row in read_table(errors, STATS_TABLE, STATS_COLUMNS):
		var where: String = "stats.csv line %d" % row.line
		if not row.get_value("stat").is_valid_identifier():
			errors.append("%s: stat \"%s\" must be letters, digits and _" % [where, row.get_value("stat")])
		elif row.get_value("kind") not in KINDS:
			errors.append("%s: kind \"%s\" must be one of %s" % [where, row.get_value("kind"), ", ".join(KINDS)])
		elif rules.stat_kinds.has(StringName(row.get_value("stat"))):
			errors.append("%s: %s is listed twice" % [where, row.get_value("stat")])
		else:
			rules.stat_kinds[StringName(row.get_value("stat"))] = row.get_value("kind")
	for row in read_table(errors, ROLES_TABLE, ROLES_COLUMNS):
		var where: String = "roles.csv line %d" % row.line
		if rules.roles.has(row.get_value("role")):
			errors.append("%s: role %s is listed twice" % [where, row.get_value("role")])
		if row.get_value("group") == WEAPON_GROUP:
			for column in ["melee", "splash"]:
				if row.get_value(column) not in ["0", "1"]:
					errors.append("%s: %s must be 1 or 0 for a weapon" % [where, column])
			if not row.get_value("attack_range").is_valid_float():
				errors.append("%s: attack_range must be a number for a weapon" % where)
		rules.roles[row.get_value("role")] = row
	for row in read_table(errors, SLOT_RULES_TABLE, SLOT_RULES_COLUMNS):
		var where: String = "slot_rules.csv line %d" % row.line
		var slot: int = EquipmentData.slot_from_name(row.get_value("slot"))
		if slot < 0 or slot in EquipmentData.LOOK_SLOTS:
			errors.append("%s: unknown item slot \"%s\"" % [where, row.get_value("slot")])
		if not row.get_value("scale").is_valid_float():
			errors.append("%s: scale \"%s\" must be a number" % [where, row.get_value("scale")])
		if row.get_value("drawn") not in ["0", "1"]:
			errors.append("%s: drawn must be 1 or 0" % where)
		rules.slots[row.get_value("slot")] = row
	_read_stat_table(errors, rules, TIER_RULES_TABLE, TIER_RULES_FIRST, rules.tiers, rules.roles)
	_read_stat_table(errors, rules, SLOT_BONUSES_TABLE, SLOT_BONUSES_FIRST, rules.slot_bonuses, rules.slots)
	return rules


## tier_rules.csv / slot_bonuses.csv: "<role or slot>:<tier index>" -> {stat: value} (zeros left out).
static func _read_stat_table(errors: Array[String], rules: Rules, path: String, first: Array[String],
		into: Dictionary, known: Dictionary) -> void:
	var stat_columns: Array[String] = []
	var rows: Array[Row] = read_table(errors, path, first, true, stat_columns)
	var file: String = path.get_file()
	for column in stat_columns:
		var kind: String = rules.stat_kinds.get(StringName(column), "")
		if kind not in ["bonus", "item"]:
			errors.append("%s: column \"%s\" is not a bonus or item stat in stats.csv" % [file, column])
	for row in rows:
		var where: String = "%s line %d" % [file, row.line]
		var owner: String = row.get_value(first[0])
		var tier: int = tier_index(row.get_value("tier"))
		if not known.has(owner):
			errors.append("%s: %s \"%s\" is not in %s" % [where, first[0], owner,
				"roles.csv" if first[0] == "role" else "slot_rules.csv"])
		if tier < 0:
			errors.append("%s: tier \"%s\" must be one of %s" % [where, row.get_value("tier"),
				", ".join(EquipmentData.TIER_NAMES)])
			continue
		var key: String = "%s:%d" % [owner, tier]
		if into.has(key):
			errors.append("%s: %s tier %s is given twice" % [where, owner, row.get_value("tier")])
		var values: Dictionary = {}
		for column in stat_columns:
			var text: String = row.get_value(column)
			if text.is_empty():
				continue
			if not text.is_valid_float():
				errors.append("%s: %s \"%s\" must be a number" % [where, column, text])
			elif text.to_float() != 0.0:
				values[StringName(column)] = text.to_float()
		into[key] = values


## Basic shape of an item row. The full checks are the validator's job (stage 5).
static func row_errors(row: Row, rules: Rules) -> Array[String]:
	var errors: Array[String] = []
	var where: String = "items.csv line %d" % row.line
	if not row.get_value("id").is_valid_identifier():
		errors.append("%s: id \"%s\" must be letters, digits and _" % [where, row.get_value("id")])
	var slot_rule: Row = rules.slots.get(row.get_value("slot"))
	var role_rule: Row = rules.roles.get(row.get_value("role"))
	if slot_rule == null:
		errors.append("%s: slot \"%s\" is not in slot_rules.csv" % [where, row.get_value("slot")])
	if role_rule == null:
		errors.append("%s: role \"%s\" is not in roles.csv" % [where, row.get_value("role")])
	if slot_rule != null and role_rule != null and slot_rule.get_value("group") != role_rule.get_value("group"):
		errors.append("%s: a %s role (%s) can't go in the %s slot (%s)" % [where, role_rule.get_value("group"),
			row.get_value("role"), slot_rule.get_value("group"), row.get_value("slot")])
	if tier_index(row.get_value("tier")) < 0:
		errors.append("%s: tier \"%s\" must be one of %s" % [where, row.get_value("tier"), ", ".join(EquipmentData.TIER_NAMES)])
	if slot_rule != null:
		var drawn: bool = slot_rule.get_value("drawn") == "1"
		if drawn and row.get_value("sprite").is_empty():
			errors.append("%s: %s items are drawn on the character: sprite is empty" % [where, row.get_value("slot")])
		elif not drawn and not row.get_value("sprite").is_empty():
			errors.append("%s: %s items are not drawn (slot_rules.csv): leave sprite empty" % [where, row.get_value("slot")])
	for column in ["name", "source"]:
		if row.get_value(column).is_empty():
			errors.append("%s: %s is empty" % [where, column])
	return errors


## Every value of the item: stat -> number (bonus and item stats, and weapon properties for weapons).
## Tier rule x slot scale + slot bonus, then the special values (exact, not scaled). Zeros are left out.
static func item_values(row: Row, rules: Rules, errors: Array[String]) -> Dictionary:
	var where: String = "items.csv line %d" % row.line
	var tier: int = tier_index(row.get_value("tier"))
	var role_key: String = "%s:%d" % [row.get_value("role"), tier]
	if not rules.tiers.has(role_key):
		errors.append("%s: no row for role %s tier %s in tier_rules.csv" % [where, row.get_value("role"),
			row.get_value("tier")])
		return {}
	var slot_rule: Row = rules.slots[row.get_value("slot")]
	var scale: float = slot_rule.get_value("scale").to_float()
	var values: Dictionary = {}
	var rule: Dictionary = rules.tiers[role_key]
	for stat: StringName in rule:
		values[stat] = rule[stat] * scale
	var own: Dictionary = rules.slot_bonuses.get("%s:%d" % [row.get_value("slot"), tier], {})
	for stat: StringName in own:
		values[stat] = values.get(stat, 0.0) + own[stat]
	var role_rule: Row = rules.roles[row.get_value("role")]
	if role_rule.get_value("group") == WEAPON_GROUP:
		for stat in ["melee", "splash", "attack_range"]:
			values[StringName(stat)] = role_rule.get_value(stat).to_float()
	var special: Dictionary = parse_special(row.get_value("special"), where + " special", errors)
	for stat: StringName in special:
		if not rules.stat_kinds.has(stat):
			errors.append("%s special: %s is not in stats.csv" % [where, stat])
		elif rules.stat_kinds[stat] == "weapon" and role_rule.get_value("group") != WEAPON_GROUP:
			errors.append("%s special: %s is only for weapons" % [where, stat])
		values[stat] = special[stat]
	# Sorted by name (as text: StringNames don't sort alphabetically), so the files never change by themselves.
	var names: Array[String] = []
	for stat: StringName in values:
		names.append(String(stat))
	names.sort()
	var rounded: Dictionary = {}
	for stat in names:
		var value: float = snappedf(values[StringName(stat)], VALUE_STEP)
		if value != 0.0 or rules.stat_kinds.get(StringName(stat), "") == "weapon":
			rounded[StringName(stat)] = value
	return rounded


static func output_path(id: String) -> String:
	return OUTPUT_DIR + id + ".tres"


## The exact text of the generated .tres for a row.
static func item_text(row: Row, values: Dictionary, rules: Rules) -> String:
	var pairs: PackedStringArray = []
	for stat: StringName in values:
		if rules.stat_kinds.get(stat, "") == "bonus":
			pairs.append("&%s: %s" % [_quote(stat), _number(values[stat])])
	var lines: PackedStringArray = [
		"[gd_resource type=\"Resource\" script_class=\"EquipmentData\" format=3]",
		"",
		"[ext_resource type=\"Script\" path=\"%s\" id=\"1_item\"]" % EQUIPMENT_SCRIPT,
		"",
		"[resource]",
		"script = ExtResource(\"1_item\")",
		"id = &%s" % _quote(row.get_value("id")),
		"display_name = %s" % _quote(row.get_value("name")),
		"slot = %d" % EquipmentData.slot_from_name(row.get_value("slot")),
		"lpc_item = %s" % _quote(row.get_value("sprite")),
		"tier = %d" % tier_index(row.get_value("tier")),
		"role = &%s" % _quote(row.get_value("role")),
		"set_id = &%s" % _quote(row.get_value("set_id")),
		"source = &%s" % _quote(row.get_value("source")),
		"bonuses = {%s}" % ", ".join(pairs),
		"weight = %s" % _number(values.get(&"weight", 0.0)),
		"price = %s" % _number(values.get(&"price", 0.0)),
	]
	if values.has(&"melee"):
		lines.append("melee = %s" % ("true" if values[&"melee"] != 0.0 else "false"))
		lines.append("splash = %s" % ("true" if values[&"splash"] != 0.0 else "false"))
		lines.append("attack_range = %s" % _number(values[&"attack_range"]))
	return HEADER + "\n".join(lines) + "\n"


## Path -> text of every file the tables make. Errors (bad rows, duplicate ids, missing rules) go to `errors`.
static func expected_files(errors: Array[String]) -> Dictionary:
	var files: Dictionary = {}
	var rules: Rules = read_rules(errors)
	for row in read_table(errors):
		var row_problems: Array[String] = row_errors(row, rules)
		if not row_problems.is_empty():
			errors.append_array(row_problems)
			continue
		var path: String = output_path(row.get_value("id"))
		if files.has(path):
			errors.append("items.csv line %d: id \"%s\" is used twice" % [row.line, row.get_value("id")])
			continue
		files[path] = item_text(row, item_values(row, rules, errors), rules)
	return files


## Generated files that don't match the tables: edited by hand, missing, or left over from a removed row.
static func check() -> Array[String]:
	var problems: Array[String] = []
	var files: Dictionary = expected_files(problems)
	for path: String in files:
		if not FileAccess.file_exists(path):
			problems.append("%s is missing: run --generate-items" % path)
		elif FileAccess.get_file_as_string(path) != files[path]:
			problems.append("%s differs from the tables (edited by hand?): run --generate-items" % path)
	for file in _generated_on_disk():
		if not files.has(OUTPUT_DIR + file):
			problems.append("%s%s has no row in the table: run --generate-items" % [OUTPUT_DIR, file])
	return problems


## Writes every file from the tables and deletes generated files whose row is gone. Nothing is written when the
## tables have errors. Returns the errors (empty = done); `report` gets what was written / removed.
static func generate(report: Array[String]) -> Array[String]:
	var errors: Array[String] = []
	var files: Dictionary = expected_files(errors)
	if not errors.is_empty():
		return errors
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUTPUT_DIR))
	for path: String in files:
		if FileAccess.file_exists(path) and FileAccess.get_file_as_string(path) == files[path]:
			continue
		var file := FileAccess.open(path, FileAccess.WRITE)
		if file == null:
			errors.append("%s: can't write it" % path)
			continue
		file.store_string(files[path])
		report.append("written " + path)
	for file in _generated_on_disk():
		if not files.has(OUTPUT_DIR + file):
			DirAccess.remove_absolute(ProjectSettings.globalize_path(OUTPUT_DIR + file))
			report.append("removed " + OUTPUT_DIR + file)
	return errors


## Items whose row has special values, for the generator's report.
static func special_items() -> Array[String]:
	var ids: Array[String] = []
	for row in read_table([] as Array[String]):
		if not row.get_value("special").is_empty():
			ids.append(row.get_value("id"))
	return ids


## .tres files in the output folder (all of them are generated).
static func _generated_on_disk() -> Array[String]:
	var found: Array[String] = []
	for file in DirAccess.get_files_at(OUTPUT_DIR):
		if file.ends_with(".tres"):
			found.append(file)
	return found


## Always with a decimal point, so the value loads back as a float: 4 -> "4.0", 0.015 -> "0.015".
static func _number(value: float) -> String:
	var text: String = String.num(value, 3)
	return text if "." in text else text + ".0"


static func _quote(text: String) -> String:
	return "\"%s\"" % text.replace("\\", "\\\\").replace("\"", "\\\"")
