class_name ItemPipeline
extends RefCounted
## Items data pipeline (see data/items/README.md):
##   data/items/items.csv       one row per item
##   data/items/tier_rules.csv  the bonuses of every role at every tier (a torso-sized piece)
##   data/items/slot_rules.csv  how big each slot's share is (scale for the tier rule values)
## -> one generated EquipmentData .tres per item in resources/items/. The tables are the only place items are
## edited; the generated files carry a header that says so, and check() reports any that differ from what the
## tables make (edited by hand, stale or missing).
## An item's bonuses = its tier rule x its slot's scale, then its own `overrides` (special items only) set exact
## values on top. Used by tools/items/item_generator.gd (writes) and the items test (checks).

const ITEMS_TABLE: String = "res://data/items/items.csv"
const TIER_RULES_TABLE: String = "res://data/items/tier_rules.csv"
const SLOT_RULES_TABLE: String = "res://data/items/slot_rules.csv"
const OUTPUT_DIR: String = "res://resources/items/"
const EQUIPMENT_SCRIPT: String = "res://scripts/resources/equipment_data.gd"
## Columns of each table, in order.
const COLUMNS: Array[String] = ["id", "name", "slot", "tier", "role", "set_id", "sprite", "source", "overrides"]
const TIER_RULES_COLUMNS: Array[String] = ["role", "tier", "bonuses"]
const SLOT_RULES_COLUMNS: Array[String] = ["slot", "scale"]
## Bonus values are rounded to this step (0.001 = 0.1%).
const VALUE_STEP: float = 0.001
## Every generated file starts with these lines (";" lines are comments in a .tres).
const HEADER: String = "; GENERATED by tools/items/item_generator.gd from data/items/ - DO NOT EDIT.\n" \
	+ "; Change the tables, then run tools/generate_items.bat (or -- --generate-items).\n"


## One table row (column name -> text), plus where it came from for error messages.
class Row:
	var line: int
	var values: Dictionary = {}

	func get_value(column: String) -> String:
		return values.get(column, "")


## The tier and slot rules, read once per generation.
class Rules:
	## "role:tier" -> {stat: value}
	var tiers: Dictionary = {}
	## slot name -> scale
	var slot_scales: Dictionary = {}


## A table's rows, or an empty list with `errors` filled when the table can't be read.
static func read_table(errors: Array[String], path: String = ITEMS_TABLE, columns: Array[String] = COLUMNS) -> Array[Row]:
	var rows: Array[Row] = []
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		errors.append("%s: can't open it" % path)
		return rows
	var header: PackedStringArray = file.get_csv_line()
	if Array(header) != columns:
		errors.append("%s: the columns must be exactly %s (found %s)" % [path, ",".join(columns), ",".join(header)])
		return rows
	var line: int = 1
	while not file.eof_reached():
		var fields: PackedStringArray = file.get_csv_line()
		line += 1
		if fields.size() == 1 and fields[0].strip_edges().is_empty():
			continue
		if fields.size() != columns.size():
			errors.append("%s line %d: %d columns, expected %d" % [path, line, fields.size(), columns.size()])
			continue
		var row := Row.new()
		row.line = line
		for i in columns.size():
			row.values[columns[i]] = fields[i].strip_edges()
		rows.append(row)
	return rows


## "defense=4;evade=0.01" -> {&"defense": 4.0, &"evade": 0.01}. Empty text = no bonuses.
static func parse_bonuses(text: String, where: String, errors: Array[String]) -> Dictionary:
	var bonuses: Dictionary = {}
	if text.is_empty():
		return bonuses
	for pair in text.split(";", false):
		var parts: PackedStringArray = pair.split("=")
		var stat: String = parts[0].strip_edges() if parts.size() == 2 else ""
		var value: String = parts[1].strip_edges() if parts.size() == 2 else ""
		if not stat.is_valid_identifier() or not value.is_valid_float():
			errors.append("%s: \"%s\" must be stat=number (several separated by ;)" % [where, pair])
			continue
		if bonuses.has(StringName(stat)):
			errors.append("%s: %s is given twice" % [where, stat])
		bonuses[StringName(stat)] = value.to_float()
	return bonuses


static func read_rules(errors: Array[String]) -> Rules:
	var rules := Rules.new()
	for row in read_table(errors, TIER_RULES_TABLE, TIER_RULES_COLUMNS):
		var where: String = "tier_rules.csv line %d" % row.line
		if not row.get_value("tier").is_valid_int():
			errors.append("%s: tier \"%s\" must be a whole number" % [where, row.get_value("tier")])
			continue
		var key: String = _rule_key(row.get_value("role"), row.get_value("tier").to_int())
		if rules.tiers.has(key):
			errors.append("%s: role %s tier %s is given twice" % [where, row.get_value("role"), row.get_value("tier")])
		rules.tiers[key] = parse_bonuses(row.get_value("bonuses"), where, errors)
	for row in read_table(errors, SLOT_RULES_TABLE, SLOT_RULES_COLUMNS):
		var where: String = "slot_rules.csv line %d" % row.line
		if not row.get_value("scale").is_valid_float():
			errors.append("%s: scale \"%s\" must be a number" % [where, row.get_value("scale")])
			continue
		rules.slot_scales[row.get_value("slot")] = row.get_value("scale").to_float()
	return rules


## Basic shape of an item row (enough to generate it). The full checks are the validator's job (stage 5).
static func row_errors(row: Row) -> Array[String]:
	var errors: Array[String] = []
	var where: String = "items.csv line %d" % row.line
	if not row.get_value("id").is_valid_identifier():
		errors.append("%s: id \"%s\" must be letters, digits and _" % [where, row.get_value("id")])
	var slot: int = EquipmentData.slot_from_name(row.get_value("slot"))
	if slot < 0 or slot in EquipmentData.LOOK_SLOTS:
		errors.append("%s: unknown item slot \"%s\"" % [where, row.get_value("slot")])
	if not row.get_value("tier").is_valid_int() or row.get_value("tier").to_int() < 1:
		errors.append("%s: tier \"%s\" must be a whole number from 1" % [where, row.get_value("tier")])
	for column in ["name", "role", "sprite", "source"]:
		if row.get_value(column).is_empty():
			errors.append("%s: %s is empty" % [where, column])
	return errors


## The item's bonuses: its tier rule x its slot's scale, then its overrides (exact values, not scaled).
static func item_bonuses(row: Row, rules: Rules, errors: Array[String]) -> Dictionary:
	var where: String = "items.csv line %d" % row.line
	var key: String = _rule_key(row.get_value("role"), row.get_value("tier").to_int())
	if not rules.tiers.has(key):
		errors.append("%s: no tier rule for role %s tier %s (tier_rules.csv)" % [where, row.get_value("role"),
			row.get_value("tier")])
		return {}
	if not rules.slot_scales.has(row.get_value("slot")):
		errors.append("%s: no scale for slot %s (slot_rules.csv)" % [where, row.get_value("slot")])
		return {}
	var scale: float = rules.slot_scales[row.get_value("slot")]
	var bonuses: Dictionary = {}
	var rule: Dictionary = rules.tiers[key]
	for stat: StringName in rule:
		bonuses[stat] = rule[stat] * scale
	var overrides: Dictionary = parse_bonuses(row.get_value("overrides"), where + " overrides", errors)
	for stat: StringName in overrides:
		bonuses[stat] = overrides[stat]
	var rounded: Dictionary = {}
	# Sorted by name (as text: StringNames don't sort alphabetically), so the files never change by themselves.
	var stats: Array[String] = []
	for stat: StringName in bonuses:
		stats.append(String(stat))
	stats.sort()
	for stat in stats:
		var value: float = snappedf(bonuses[StringName(stat)], VALUE_STEP)
		if value != 0.0:
			rounded[StringName(stat)] = value
	return rounded


static func output_path(id: String) -> String:
	return OUTPUT_DIR + id + ".tres"


## The exact text of the generated .tres for a row.
static func item_text(row: Row, bonuses: Dictionary) -> String:
	var pairs: PackedStringArray = []
	for stat: StringName in bonuses:
		pairs.append("&%s: %s" % [_quote(stat), _number(bonuses[stat])])
	var lines: PackedStringArray = [
		"[gd_resource type=\"Resource\" script_class=\"EquipmentData\" format=3]",
		"",
		"[ext_resource type=\"Script\" path=\"%s\" id=\"1_item\"]" % EQUIPMENT_SCRIPT,
		"",
		"[resource]",
		"script = ExtResource(\"1_item\")",
		"id = &%s" % _quote(row.get_value("id")),
		"display_name = %s" % _quote(row.get_value("name")),
		"slot = %d" % EquipmentData.slot_from_name(row.get_value("slot")),
		"lpc_item = %s" % _quote(row.get_value("sprite")),
		"tier = %d" % row.get_value("tier").to_int(),
		"role = &%s" % _quote(row.get_value("role")),
		"set_id = &%s" % _quote(row.get_value("set_id")),
		"source = &%s" % _quote(row.get_value("source")),
		"bonuses = {%s}" % ", ".join(pairs),
	]
	return HEADER + "\n".join(lines) + "\n"


## Path -> text of every file the tables make. Errors (bad rows, duplicate ids, missing rules) go to `errors`.
static func expected_files(errors: Array[String]) -> Dictionary:
	var files: Dictionary = {}
	var rules: Rules = read_rules(errors)
	for row in read_table(errors):
		var row_problems: Array[String] = row_errors(row)
		if not row_problems.is_empty():
			errors.append_array(row_problems)
			continue
		var path: String = output_path(row.get_value("id"))
		if files.has(path):
			errors.append("items.csv line %d: id \"%s\" is used twice" % [row.line, row.get_value("id")])
			continue
		files[path] = item_text(row, item_bonuses(row, rules, errors))
	return files


## Generated files that don't match the tables: edited by hand, missing, or left over from a removed row.
static func check() -> Array[String]:
	var problems: Array[String] = []
	var files: Dictionary = expected_files(problems)
	for path: String in files:
		if not FileAccess.file_exists(path):
			problems.append("%s is missing: run --generate-items" % path)
		elif FileAccess.get_file_as_string(path) != files[path]:
			problems.append("%s differs from the tables (edited by hand?): run --generate-items" % path)
	for file in _generated_on_disk():
		if not files.has(OUTPUT_DIR + file):
			problems.append("%s%s has no row in the table: run --generate-items" % [OUTPUT_DIR, file])
	return problems


## Writes every file from the tables and deletes generated files whose row is gone. Nothing is written when the
## tables have errors. Returns the errors (empty = done); `report` gets what was written / removed.
static func generate(report: Array[String]) -> Array[String]:
	var errors: Array[String] = []
	var files: Dictionary = expected_files(errors)
	if not errors.is_empty():
		return errors
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUTPUT_DIR))
	for path: String in files:
		if FileAccess.file_exists(path) and FileAccess.get_file_as_string(path) == files[path]:
			continue
		var file := FileAccess.open(path, FileAccess.WRITE)
		if file == null:
			errors.append("%s: can't write it" % path)
			continue
		file.store_string(files[path])
		report.append("written " + path)
	for file in _generated_on_disk():
		if not files.has(OUTPUT_DIR + file):
			DirAccess.remove_absolute(ProjectSettings.globalize_path(OUTPUT_DIR + file))
			report.append("removed " + OUTPUT_DIR + file)
	return errors


## Items whose row has overrides (the special items), for the generator's report.
static func special_items() -> Array[String]:
	var ids: Array[String] = []
	for row in read_table([] as Array[String]):
		if not row.get_value("overrides").is_empty():
			ids.append(row.get_value("id"))
	return ids


## .tres files in the output folder (all of them are generated).
static func _generated_on_disk() -> Array[String]:
	var found: Array[String] = []
	for file in DirAccess.get_files_at(OUTPUT_DIR):
		if file.ends_with(".tres"):
			found.append(file)
	return found


static func _rule_key(role: String, tier: int) -> String:
	return "%s:%d" % [role, tier]


## Always with a decimal point, so the value loads back as a float: 4 -> "4.0", 0.015 -> "0.015".
static func _number(value: float) -> String:
	var text: String = String.num(value, 3)
	return text if "." in text else text + ".0"


static func _quote(text: String) -> String:
	return "\"%s\"" % text.replace("\\", "\\\\").replace("\"", "\\\"")
